"""Counterfactual uplift ledger and multi-touch causal attribution engine.

Calculates scientifically valid incremental recovery metrics:
1. **5% Randomized Control Holdout Group**:
   Partitions payment recovery cases into active Treatment (95%) and passive
   Control Holdout (5%) to establish unconfounded baseline recovery rates.
2. **True Incremental Recovery Calculation**:
   - Incremental Recovery (₹) = Gross Recovered (Treatment) - Counterfactual Baseline.
   - Incremental Uplift (%) = Treatment Recovery Rate (%) - Control Recovery Rate (%).
3. **Multi-Touch Causal Attribution Engine**:
   Distributes recovered revenue across recovery touchpoints
   (``WEBHOOK_INGESTION``, ``WHATSAPP_LINK``, ``VOICE_BOT``, ``PTP_COMMITMENT``, ``MANDATE_RETRY``)
   using Linear, First-Touch, Last-Touch, or Time-Decay attribution models.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Sequence


# ---------------------------------------------------------------------------
# Enums & Models
# ---------------------------------------------------------------------------

class AttributionModel(str, Enum):
    """Multi-touch attribution models."""
    LINEAR = "linear"
    FIRST_TOUCH = "first_touch"
    LAST_TOUCH = "last_touch"
    TIME_DECAY = "time_decay"


@dataclass(frozen=True)
class UpliftLedgerEntry:
    """Individual case entry in the counterfactual uplift ledger.

    Attributes
    ----------
    case_id:
        Recovery case or attempt ID.
    customer_id:
        Customer identifier.
    amount_inr:
        Transaction amount in INR.
    assigned_arm:
        Experimental arm: ``"TREATMENT"`` or ``"CONTROL_HOLDOUT"``.
    touchpoints:
        Sequence of touchpoints customer interacted with.
    recovered:
        Whether the payment was successfully recovered.
    recovered_amount_inr:
        Amount recovered in INR (amount if recovered else 0.0).
    counterfactual_baseline_inr:
        Expected organic recovery value without AI intervention.
    incremental_uplift_inr:
        Net incremental recovery value generated by AI.
    attribution_weights:
        Fractional credit assigned to each touchpoint.
    """

    case_id: str
    customer_id: str
    amount_inr: float
    assigned_arm: str
    touchpoints: tuple[str, ...]
    recovered: bool
    recovered_amount_inr: float
    counterfactual_baseline_inr: float
    incremental_uplift_inr: float
    attribution_weights: dict[str, float]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class CounterfactualUpliftSummary:
    """Aggregate summary of counterfactual causal recovery uplift."""

    total_cases: int
    treatment_count: int
    control_holdout_count: int
    treatment_recovery_rate_pct: float
    control_recovery_rate_pct: float
    incremental_uplift_pct: float
    gross_recovered_inr: float
    counterfactual_baseline_inr: float
    true_incremental_recovery_inr: float
    channel_attribution_inr: dict[str, float]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Multi-Touch Attribution Logic
# ---------------------------------------------------------------------------

def compute_multi_touch_attribution(
    touchpoints: Sequence[str],
    model: AttributionModel | str = AttributionModel.LINEAR,
) -> dict[str, float]:
    """Calculate fractional attribution weights across sequence touchpoints."""
    if not touchpoints:
        return {}

    n = len(touchpoints)
    model_enum = AttributionModel(model) if isinstance(model, str) else model

    if model_enum == AttributionModel.FIRST_TOUCH:
        weights = {tp: 0.0 for tp in touchpoints}
        weights[touchpoints[0]] = 1.0
        return weights

    if model_enum == AttributionModel.LAST_TOUCH:
        weights = {tp: 0.0 for tp in touchpoints}
        weights[touchpoints[-1]] = 1.0
        return weights

    if model_enum == AttributionModel.TIME_DECAY:
        # Exponential weights with half-life on older touches
        raw_weights = [2 ** (i) for i in range(n)]
        total_raw = sum(raw_weights)
        weights_dict: dict[str, float] = {}
        for tp, rw in zip(touchpoints, raw_weights):
            weights_dict[tp] = weights_dict.get(tp, 0.0) + (rw / total_raw)
        return {k: round(v, 4) for k, v in weights_dict.items()}

    # Default: Linear Attribution
    weight_per_touch = 1.0 / n
    weights_dict = {}
    for tp in touchpoints:
        weights_dict[tp] = weights_dict.get(tp, 0.0) + weight_per_touch
    return {k: round(v, 4) for k, v in weights_dict.items()}


# ---------------------------------------------------------------------------
# Deterministic Holdout Partitioning
# ---------------------------------------------------------------------------

def assign_holdout_arm(
    case_id: str,
    holdout_pct: float = 0.05,
    salt: str = "recoverai_holdout_v1",
) -> str:
    """Deterministically assign a case to TREATMENT or CONTROL_HOLDOUT using SHA256."""
    key = f"{salt}:{case_id}"
    digest = hashlib.sha256(key.encode("utf-8")).hexdigest()
    ratio = (int(digest[:8], 16) % 10000) / 10000.0
    return "CONTROL_HOLDOUT" if ratio < holdout_pct else "TREATMENT"


# ---------------------------------------------------------------------------
# Counterfactual Uplift Ledger Generator
# ---------------------------------------------------------------------------

def compute_counterfactual_uplift_ledger(
    records: Sequence[dict[str, Any]],
    holdout_pct: float = 0.05,
    attribution_model: AttributionModel | str = AttributionModel.LINEAR,
) -> tuple[list[UpliftLedgerEntry], CounterfactualUpliftSummary]:
    """Compute the unconfounded counterfactual uplift ledger for a batch of cases.

    Parameters
    ----------
    records:
        Sequence of dictionaries containing at least:
        - ``case_id`` (str)
        - ``customer_id`` (str)
        - ``amount_inr`` (float)
        - ``recovered`` (bool | int)
        - Optional: ``touchpoints`` (list[str]), ``assigned_arm`` (str)
    """
    if not records:
        empty_summary = CounterfactualUpliftSummary(
            total_cases=0,
            treatment_count=0,
            control_holdout_count=0,
            treatment_recovery_rate_pct=0.0,
            control_recovery_rate_pct=0.0,
            incremental_uplift_pct=0.0,
            gross_recovered_inr=0.0,
            counterfactual_baseline_inr=0.0,
            true_incremental_recovery_inr=0.0,
            channel_attribution_inr={},
        )
        return [], empty_summary

    # Step 1: Assign holdout arms & separate groups
    treatment_records = []
    control_records = []

    for r in records:
        cid = str(r["case_id"])
        arm = r.get("assigned_arm") or assign_holdout_arm(cid, holdout_pct)
        r_copy = dict(r)
        r_copy["assigned_arm"] = arm
        if arm == "CONTROL_HOLDOUT":
            control_records.append(r_copy)
        else:
            treatment_records.append(r_copy)

    # Step 2: Compute empirical Control Baseline Recovery Rate
    control_count = len(control_records)
    if control_count > 0:
        control_recovered_count = sum(1 for r in control_records if bool(r.get("recovered")))
        control_recovery_rate = control_recovered_count / control_count
    else:
        # Fallback conservative organic baseline rate if holdout sample is tiny
        control_recovery_rate = 0.12

    # Step 3: Evaluate Treatment cases against Counterfactual Baseline
    treatment_count = len(treatment_records)
    treatment_recovered_count = 0
    gross_recovered_inr = 0.0
    treatment_total_at_risk_inr = 0.0
    channel_attribution_inr: dict[str, float] = {}

    ledger_entries: list[UpliftLedgerEntry] = []

    for r in treatment_records:
        cid = str(r["case_id"])
        cust_id = str(r.get("customer_id", "cust_unknown"))
        amt = float(r["amount_inr"])
        rec = bool(r.get("recovered"))
        treatment_total_at_risk_inr += amt

        touchpoints = tuple(r.get("touchpoints") or ["DEFAULT_RETRY_ACTION"])
        weights = compute_multi_touch_attribution(touchpoints, attribution_model) if rec else {}

        rec_amt = amt if rec else 0.0
        cf_baseline_amt = round(amt * control_recovery_rate, 2)
        incremental_amt = round(max(0.0, rec_amt - cf_baseline_amt) if rec else 0.0, 2)

        if rec:
            treatment_recovered_count += 1
            gross_recovered_inr += rec_amt
            for tp, w in weights.items():
                attributed_val = incremental_amt * w
                channel_attribution_inr[tp] = channel_attribution_inr.get(tp, 0.0) + attributed_val

        ledger_entries.append(
            UpliftLedgerEntry(
                case_id=cid,
                customer_id=cust_id,
                amount_inr=amt,
                assigned_arm="TREATMENT",
                touchpoints=touchpoints,
                recovered=rec,
                recovered_amount_inr=rec_amt,
                counterfactual_baseline_inr=cf_baseline_amt,
                incremental_uplift_inr=incremental_amt,
                attribution_weights=weights,
            )
        )

    # Also log control holdout cases in ledger
    for r in control_records:
        cid = str(r["case_id"])
        cust_id = str(r.get("customer_id", "cust_unknown"))
        amt = float(r["amount_inr"])
        rec = bool(r.get("recovered"))
        rec_amt = amt if rec else 0.0
        ledger_entries.append(
            UpliftLedgerEntry(
                case_id=cid,
                customer_id=cust_id,
                amount_inr=amt,
                assigned_arm="CONTROL_HOLDOUT",
                touchpoints=("NO_INTERVENTION_HOLDOUT",),
                recovered=rec,
                recovered_amount_inr=rec_amt,
                counterfactual_baseline_inr=rec_amt,
                incremental_uplift_inr=0.0,
                attribution_weights={},
            )
        )

    treatment_recovery_rate = (treatment_recovered_count / treatment_count) if treatment_count > 0 else 0.0
    counterfactual_baseline_total_inr = round(treatment_total_at_risk_inr * control_recovery_rate, 2)
    true_incremental_recovery_inr = round(max(0.0, gross_recovered_inr - counterfactual_baseline_total_inr), 2)
    incremental_uplift_pct = round(max(0.0, (treatment_recovery_rate - control_recovery_rate) * 100), 2)

    summary = CounterfactualUpliftSummary(
        total_cases=len(records),
        treatment_count=treatment_count,
        control_holdout_count=control_count,
        treatment_recovery_rate_pct=round(treatment_recovery_rate * 100, 2),
        control_recovery_rate_pct=round(control_recovery_rate * 100, 2),
        incremental_uplift_pct=incremental_uplift_pct,
        gross_recovered_inr=round(gross_recovered_inr, 2),
        counterfactual_baseline_inr=counterfactual_baseline_total_inr,
        true_incremental_recovery_inr=true_incremental_recovery_inr,
        channel_attribution_inr={k: round(v, 2) for k, v in channel_attribution_inr.items()},
    )

    return ledger_entries, summary
